spring.application.name=MyService-3-arch
spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
spring.datasource.password=root@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
management.endpoints.web.exposure.include=health,info,metrics
server.port=8080

